export type Role = 'admin' | 'pumpOwner' | 'employee';

export type FuelType = 'HSD' | 'MS';

export type RequestStatus = 'pending' | 'filled' | 'cancelled' | 'expired';

export type BillStatus = 'draft' | 'raised' | 'paid';

export type DiscountMode = 'per_liter' | 'flat';

export interface User {
  id: string;
  role: Role;
  name: string;
  email: string;
  pumpId?: string;
  /** Set only for company admin users */
  companyId?: string;
  createdAt: string;
}

export interface Company {
  id: string;
  name: string;
  gstin?: string;
}

/** Many-to-many: one pump can serve multiple companies */
export interface CompanyPumpLink {
  id: string;
  companyId: string;
  pumpId: string;
  joinedAt: string;
  active: boolean;
}

/** Invite code generated by a company; pump redeems to create a link */
export interface PumpInvite {
  id: string;
  companyId: string;
  code: string;
  createdAt: string;
  expiresAt?: string;
  redeemedByPumpId?: string;
  redeemedAt?: string;
}

export interface Pump {
  id: string;
  name: string;
  address: string;
  contact: string;
  ownerUserId: string;
  gstin?: string;
}

export interface FuelRequest {
  id: string;
  companyId: string;
  pumpId: string;
  vehicleNo: string;
  fuel: FuelType;
  qty: number;
  status: RequestStatus;
  notes?: string;
  extraCash?: number;
  isTankFull?: boolean;
  createdAt: string;
  filledBy?: string;
  txnId?: string;
}

export interface Transaction {
  id: string;
  requestId: string;
  companyId: string;
  pumpId: string;
  vehicleNo: string;
  fuel: FuelType;
  actualQty: number;
  rate: number;
  gross: number;
  vehiclePhoto?: string;
  receiptPhoto?: string;
  extraCash: number;
  advance: number;
  voucherNo?: string;
  createdAt: string;
  filledByUserId: string;
  billId?: string;
}

export interface FuelDiscount {
  mode: DiscountMode;
  value: number;
}

export interface Bill {
  id: string;
  pumpId: string;
  companyId: string;
  billNo: string;
  period: { from: string; to: string };
  generatedAt: string;
  itemIds: string[];
  discountHSD: FuelDiscount;
  discountMS: FuelDiscount;
  previousBalance: number;
  status: BillStatus;
  paymentRefNo?: string;
  paymentProof?: string;
}
